# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181022_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='\u4e0d\u516c\u958b', max_length=10)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Mood')),
            ],
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='pphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pmodel',
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
        migrations.DeleteModel(
            name='PPhoto',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
